version: '3'

services:
  php_env:
    build:
      context: ./docker
    args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    container_name: app_fpm
    restart: always
    volumes:
      - ./data/www:/var/www/html
    ports:
      - "8000:8000"
