version: '3'

services:
  fpm:
    build:
      context: ./fpm
    container_name: app_fpm
    restart: always
    volumes:
      - ./../www:/var/www/html
    ports: 
      - "8000:8000"
    extra_hosts:
      - "lara.local:127.0.0.1"
    networks:
      app_net:

networks:
  app_net:
