FROM php:7.4-fpm

# Get user id and group id from arguments.
ARG UID
ARG GID

# Add user.
RUN sed -i -e"s/^user\s=\swww-data/user = serveruser/" /usr/local/etc/php-fpm.d/www.conf && \
  sed -i -e"s/^group\s=\swww-data/group = serveruser/" /usr/local/etc/php-fpm.d/www.conf && \
  sed -i -e"s/^;php_admin_value\[memory_limit\]\s=\s32M/php_admin_value[memory_limit] = 256M\nphp_admin_value[max_input_vars] = 5000/" /usr/local/etc/php-fpm.d/www.conf && \
  echo "\ncatch_workers_output = yes\nphp_admin_value[error_log] = /var/log/fpm-php.www.log\nphp_admin_flag[log_errors] = on\n" >> /usr/local/etc/php-fpm.d/www.conf && \
  touch /var/log/fpm-php.www.log && chmod 777 /var/log/fpm-php.www.log && \
  groupadd -r serveruser -g $GID && useradd -ms /bin/bash serveruser -u $UID -g $GID

# GD
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev libjpeg-dev libwebp-dev libzip-dev \
        git wget nano netcat zip curl unzip default-mysql-client \
    && docker-php-ext-configure zip --with-zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-zip \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip && \
      php -m | grep -q 'zip'

RUN docker-php-ext-install pdo_mysql

# Install node
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash && \
    apt-get install -y nodejs 
RUN npm install -g @vue/cli

# Opcache.
RUN docker-php-ext-configure opcache --enable-opcache && \
  docker-php-ext-install opcache

# Xdebug
RUN pecl install xdebug-2.8.1 \
    && docker-php-ext-enable xdebug

# Install composer.
RUN cd ~
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN rm -rf composer-setup.php
USER serveruser
WORKDIR /home/serveruser
RUN echo "PATH=$PATH:~/.composer/vendor/bin" >> ~/.bashrc

# Install phpunit.
USER root
RUN wget https://phar.phpunit.de/phpunit.phar && \
  chmod +x phpunit.phar && \
  mv phpunit.phar /usr/local/bin/phpunit

USER serveruser

WORKDIR /home/serveruser

ENTRYPOINT ["php-fpm"]
